#!/bin/bash
BOX_NAME='alpine'
if [[ $DISTROBOX_ENTER_PATH || $TOOLBOX_PATH ]];then
	cargo $@
elif [[ $(command -v distrobox-enter) ]];then
	distrobox-enter $BOX_NAME -- cargo $@
elif [[ $(command -v toolbox) ]];then
	toolbox run cargo $@
else
	echo "no distrobox or toolbox."
fi

