#!/bin/bash
if [[ $(nmcli networking connectivity) == "full" ]];then
	echo "$(date) emailsync start"
	mbsync -c ~/.config/mbsyncrc -a 2>&1
	echo "$(date) emailsync done"
else
	echo "no networking; not syncing email."
fi
