#!/usr/bin/env sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# If no url given. Opens browser. For using script as $BROWSER.
#BROWSER='firefox'
if [[ "$XDG_SESSION_TYPE" == "wayland" ]];then
	export MOZ_ENABLE_WAYLAND=1
fi
BROWSER='firefox'
TERMINAL='gnome-terminal'
EDITOR='vim'
[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
	*mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*|*videos.lukesmith.xyz*|*www.crunchyroll.com*|*odysee.com*|*tilvids.com*|*yewtu.be*|*invidious.snopyta.org*)
		if [[ "$XDG_SESSION_DESKTOP" == "gnome" ]];then
            setsid gnome-session-inhibit --reason linkhandler-mpv --inhibit suspend --inhibit idle mpv -quiet "$1" >/dev/null 2>&1 &
        else
		    setsid mpv -quiet "$1" >/dev/null 2>&1 &
        fi
        ;;
	*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$1" -o "/tmp/$(echo "$1" | sed "s/.*\///")" && imv "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source*)
		setsid tsp curl -LO "$1" >/dev/null 2>&1 & ;;
    gemini://*)
        alacritty -e amfora $1 2>&1 & ;;
	*)
		if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
		else setsid $BROWSER "$1" >/dev/null 2>&1 & fi ;;
esac
