#!/bin/bash
ips=$(nmap -sP 192.168.1.0/24 2>/dev/null | grep 'scan report' | awk '{print $NF}' |sed 's/(//;s/)//')
#ips=$(nmap -sP 10.0.0.0/24 2>/dev/null | grep 'scan report' | awk '{print $NF}' |sed 's/(//;s/)//')

for ip in $ips
do
  mac=$(arp $ip | cut -f 4 -d' ')
  ptr=$(dig -x $ip| grep PTR |tail -n 1|awk '{ print $NF}')
  if [ $ptr == 'PTR' ]
  then
    ptr="none"
  fi
  echo -e "$ip\t$mac\t$ptr;"
done
